
package Vistas;

import Modelo.*;
import Controlador.*;

import Controlador.EnumDepartamento;
import Controlador.EnumTipoCalle;
import Controlador.EnumZona;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 * Branch office form
 * @author Carlos
 */

public class SucursalForm extends javax.swing.JDialog {

    Conexion conexion = new Conexion();
    Connection connection;
    Statement st;
    ResultSet rs;
    DefaultTableModel contenidoTablaEmpleados;
    DefaultTableModel contenidoTablaDepartamentos;
    ComboBoxModel modelEnumDepartamentos;
    ComboBoxModel modelEnumZona;
    ComboBoxModel modelEnumTipoCalle;

    public SucursalForm(java.awt.Frame parent, boolean modal) {
	super(parent, modal);

	modelEnumDepartamentos = new DefaultComboBoxModel(EnumDepartamento.values());
	modelEnumZona = new DefaultComboBoxModel(EnumZona.values());
	modelEnumTipoCalle = new DefaultComboBoxModel(EnumTipoCalle.values());

	initComponents();
	this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtInfo1 = new javax.swing.JLabel();
        txtNameBranch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSaveNewEmp = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCancelNewEmp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbDepartamento = new javax.swing.JComboBox<>();
        cbZona = new javax.swing.JComboBox<>();
        cbTipoDireccion = new javax.swing.JComboBox<>();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtNum3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Sucursal");

        bg.setBackground(new java.awt.Color(183, 155, 250));
        bg.setPreferredSize(new java.awt.Dimension(637, 452));

        txtInfo1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtInfo1.setForeground(new java.awt.Color(255, 255, 255));
        txtInfo1.setText("Agregar Nueva Sucursal");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Sucursal");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departamento");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Zona");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo direccion");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("#");

        btnSaveNewEmp.setBackground(new java.awt.Color(81, 141, 173));
        btnSaveNewEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveNewEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveNewEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveNewEmpMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Guardar");

        javax.swing.GroupLayout btnSaveNewEmpLayout = new javax.swing.GroupLayout(btnSaveNewEmp);
        btnSaveNewEmp.setLayout(btnSaveNewEmpLayout);
        btnSaveNewEmpLayout.setHorizontalGroup(
            btnSaveNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaveNewEmpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        btnSaveNewEmpLayout.setVerticalGroup(
            btnSaveNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSaveNewEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCancelNewEmp.setBackground(new java.awt.Color(218, 12, 86));
        btnCancelNewEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelNewEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelNewEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelNewEmpMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cancelar");

        javax.swing.GroupLayout btnCancelNewEmpLayout = new javax.swing.GroupLayout(btnCancelNewEmp);
        btnCancelNewEmp.setLayout(btnCancelNewEmpLayout);
        btnCancelNewEmpLayout.setHorizontalGroup(
            btnCancelNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelNewEmpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        btnCancelNewEmpLayout.setVerticalGroup(
            btnCancelNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelNewEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-");

        cbDepartamento.setModel(modelEnumDepartamentos);

        cbZona.setModel(modelEnumZona);

        cbTipoDireccion.setModel(modelEnumTipoCalle);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/branch64.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtInfo1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbZona, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(cbTipoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(2, 2, 2)
                                .addComponent(txtNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNameBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnSaveNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtInfo1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTipoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(86, 86, 86)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelNewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveNewEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveNewEmpMouseClicked

	int departamentoOption = cbDepartamento.getSelectedIndex();
	int zonaOption = cbZona.getSelectedIndex();
	int tipoCalleOption = cbTipoDireccion.getSelectedIndex();

	// String txt address
	
	String numero1 = txtNum1.getText();
	String numero2 = txtNum2.getText();
	String numero3 = txtNum3.getText();

	String zonaOptionT = "";
	String tipoCalleOptionT = "";
	String departamentoOptionT = "";

	//condionals departamento index values
	if (departamentoOption == 0) {
	    departamentoOptionT = "Amazonas";
	} else if (departamentoOption == 1) {
	    departamentoOptionT = "Antioquia";
	} else if (departamentoOption == 2) {
	    departamentoOptionT = "Arauca";
	} else if (departamentoOption == 3) {
	    departamentoOptionT = "Atlántico";
	} else if (departamentoOption == 4) {
	    departamentoOptionT = "Bogotá";
	} else if (departamentoOption == 5) {
	    departamentoOptionT = "Bolívar";
	} else if (departamentoOption == 6) {
	    departamentoOptionT = "Boyacá";
	} else if (departamentoOption == 7) {
	    departamentoOptionT = "Caldas";
	} else if (departamentoOption == 8) {
	    departamentoOptionT = "Caquetá";
	} else if (departamentoOption == 9) {
	    departamentoOptionT = "Casanare";
	} else if (departamentoOption == 10) {
	    departamentoOptionT = "Cauca";
	} else if (departamentoOption == 11) {
	    departamentoOptionT = "Cesar";
	} else if (departamentoOption == 12) {
	    departamentoOptionT = "Chocó";
	} else if (departamentoOption == 13) {
	    departamentoOptionT = "Córdoba";
	} else if (departamentoOption == 14) {
	    departamentoOptionT = "Cundinamarca";
	} else if (departamentoOption == 15) {
	    departamentoOptionT = "Guainía";
	} else if (departamentoOption == 16) {
	    departamentoOptionT = "Guaviare";
	} else if (departamentoOption == 17) {
	    departamentoOptionT = "Huila";
	} else if (departamentoOption == 18) {
	    departamentoOptionT = "La Guajira";
	} else if (departamentoOption == 19) {
	    departamentoOptionT = "Magdalena";
	} else if (departamentoOption == 20) {
	    departamentoOptionT = "Meta";
	} else if (departamentoOption == 21) {
	    departamentoOptionT = "Nariño";
	} else if (departamentoOption == 22) {
	    departamentoOptionT = "Norte de Santander";
	} else if (departamentoOption == 23) {
	    departamentoOptionT = "Putumayo";
	} else if (departamentoOption == 24) {
	    departamentoOptionT = "Quindío";
	} else if (departamentoOption == 25) {
	    departamentoOptionT = "Risaralda";
	} else if (departamentoOption == 26) {
	    departamentoOptionT = "San Andrés y Providencia";
	} else if (departamentoOption == 27) {
	    departamentoOptionT = "Santander";
	} else if (departamentoOption == 28) {
	    departamentoOptionT = "Sucre";
	} else if (departamentoOption == 29) {
	    departamentoOptionT = "Tolima";
	} else if (departamentoOption == 30) {
	    departamentoOptionT = "Valle del Cauca";
	} else if (departamentoOption == 31) {
	    departamentoOptionT = "Vaupés";
	} else {
	    departamentoOptionT = "Vichada";
	}

	// condionals zone by index
	if (zonaOption == 0) {
	    zonaOptionT = "Urbana";

	} else {
	    zonaOptionT = "Rural";
	}

	// condionals tipoCalle by index
	if (tipoCalleOption == 0) {
	    tipoCalleOptionT = "Avenida";

	} else if (tipoCalleOption == 1) {
	    tipoCalleOptionT = "Calle";
	} else if (tipoCalleOption == 2) {
	    tipoCalleOptionT = "Carrera";
	} else if (tipoCalleOption == 3) {
	    tipoCalleOptionT = "Circunvalar";
	} else if (tipoCalleOption == 4) {
	    tipoCalleOptionT = "Esquina";
	} else if (tipoCalleOption == 5) {
	    tipoCalleOptionT = "Transversal";
	} else {
	    tipoCalleOptionT = "Otro";
	}

	// Query direccion
	String queryAddress = "INSERT INTO `direccion`(`zona`, `tipoCalle`, `numero1`, `numero2`, `numero3`, `nombreDepartamento`) VALUES ('" + zonaOptionT + "','" + tipoCalleOptionT + "','" + numero1 + "','" + numero2 + "','" + numero3 + "','" + departamentoOptionT + "')";

	System.out.println(queryAddress);

	try {
	    connection = conexion.getConnection();
	    st = connection.createStatement();
	    st.executeUpdate(queryAddress);

	    // query idDirecion with msg
	    String queryIdDireccion = "SELECT IdDireccion FROM `direccion` WHERE nombreDepartamento = '" + departamentoOptionT + "' AND zona ='" + zonaOptionT + "' AND tipoCalle ='" + tipoCalleOptionT + "' AND numero1 = '" + numero1 + "' AND numero2 = '" + numero2 + "'AND numero3 = '" + numero3 + "' ;";
	    System.out.println(queryIdDireccion);

	    try {
		connection = conexion.getConnection();
		st = connection.createStatement();
		rs = st.executeQuery(queryIdDireccion);

		while (rs.next()) {
		    int idDireccion = rs.getInt("idDireccion");

		    String sucursal = txtNameBranch.getText();

		    String querySucursal = "INSERT INTO `sucursal`(`nombreSucursal`, `FK_nit`, `FK_idDireccion`) VALUES ('" + sucursal + "',999999991," + idDireccion + ")";

		    try {
			connection = conexion.getConnection();
			st = connection.createStatement();
			st.executeUpdate(querySucursal);
			System.out.println("querrySucursal:  " + querySucursal);
			this.dispose();
			//Show msg when the registry of a new employee its successful 
			

		    } catch (SQLException e) {
			System.out.println(e);

		    }

		}

	    } catch (SQLException e) {
		System.out.println(e);

	    }

	    //Show msg when the registry of a new employee its successful 
	    JOptionPane.showMessageDialog(this, "La sucursal ha sido creada", "", JOptionPane.INFORMATION_MESSAGE);

	} catch (SQLException e) {
	    System.out.println(e);
	    JOptionPane.showMessageDialog(this, "No se pudo crear la sucursal", "", JOptionPane.ERROR_MESSAGE);

	}

    }//GEN-LAST:event_btnSaveNewEmpMouseClicked

    private void btnSaveNewEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveNewEmpMouseEntered
	//hover effect button  enter
	btnSaveNewEmp.setBackground(new Color(17, 204, 250));
    }//GEN-LAST:event_btnSaveNewEmpMouseEntered

    private void btnSaveNewEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveNewEmpMouseExited
	// hover effect button exit
	btnSaveNewEmp.setBackground(new Color(81, 141, 173));
    }//GEN-LAST:event_btnSaveNewEmpMouseExited

    private void btnCancelNewEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelNewEmpMouseClicked
	this.dispose();
    }//GEN-LAST:event_btnCancelNewEmpMouseClicked

    private void btnCancelNewEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelNewEmpMouseEntered
	//hover effect button  enter
	btnCancelNewEmp.setBackground(new Color(17, 204, 250));
    }//GEN-LAST:event_btnCancelNewEmpMouseEntered

    private void btnCancelNewEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelNewEmpMouseExited
	// hover effect button exit
	btnCancelNewEmp.setBackground(new Color(218, 12, 86));
    }//GEN-LAST:event_btnCancelNewEmpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(SucursalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(SucursalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(SucursalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(SucursalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		SucursalForm dialog = new SucursalForm(new javax.swing.JFrame(), true);
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		    @Override
		    public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
		    }
		});
		dialog.setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCancelNewEmp;
    private javax.swing.JPanel btnSaveNewEmp;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JComboBox<String> cbTipoDireccion;
    private javax.swing.JComboBox<String> cbZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtInfo1;
    private javax.swing.JTextField txtNameBranch;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    // End of variables declaration//GEN-END:variables
}
